### ISSUE TITLE
Rule blocked: CORERULES-9630 - need a way to compare ordering of records when sorted according to "previous" or "next" references

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/cdisc-rules-engine#1024]
**Links to related JIRA Tickets**
- https://jira.cdisc.org/projects/CORERULES/issues/CORERULES-9630

**Rule Information**
- **Standard**: USDM
- **Rule ID**: DDF00087
- **Rule Description**: Encounter ordering using previous and next attributes is expected to be consistent with the order of corresponding scheduled activity instances according to their specified default conditions.

**Describe the problem**
There doesn't appear to be any existing operators or operations that can be used to perform this check - mainly because the ordering relies on referencing the "previous" or "next" record in the series by storing its identifier value in variables that might have different names.

**Describe the solution**
To perform this check, I think it would be necessary to generate two ordered lists of encounter id values:
1. An ordered list of `id` values from the `Encounter` dataset, where ordering is based on the value of `nextId` (which holds the `id` of the next encounter in the series).
2. An ordered list of `encounterId` values from the `ScheduledActivityInstance` dataset, where ordering is based on the value of `defaultConditionId` (which holds the `id` of the next scheduled instance in the series). Complications include:
    - `defaultConditionId` can specify the `id` value for either a scheduled activity instance (a record in the `ScheduledActivityInstance` dataset) or a scheduled decision instance (a record in the `ScheduledDecisionInstance` dataset).  It would therefore be necessary to follow the ordered series across datasets.
    - More than one scheduled instance can be associated with the same encounter.

I imagine the ordered lists would be generated using an operation that has parameters including:
- dataset name(s) (more than one allowed if the sequence traverses datasets),
- ordering variable name (e.g., `previousId`, `nextId`, `defaultConditionId`) - it should be assumed that this variable would contain the value of the `id` variable for previous/next record,
- direction of ordering references (e.g., `forward` or `reverse` to indicate when the ordering variable indicates the previous or next record in the ordered sequence) - ordered lists should be returned in "forward" order, but may be built in "reverse" order (e.g., if the specified ordering variable is `previousId`).
- sequenced value variable name (the attribute contain the values to be added to the ordered list - e.g., `id`, `encounterId`)
- maybe an option to determine if the list should contain all values or only non-repeated values.

The ordered lists would then need to be compared with a warning being reported if they're different. This could possibly be a new operator (e.g., `has_same_ordering_as`/`does_not_have_same_ordering_as`) that takes an ordered list as both `name` and `value`, and maybe has an parameter that indicates if missing values are allowed (i.e., whether values that appear in only one of the lists should indicate a different ordering).

The rule would probably have to be dataset-level check (`Sensitivity = Dataset`) as it would be difficult to report incorrect ordering at the record level.

**Proposed rule logic**
```yaml
Check:
  all:
    - name: $encounter_list
      operator: does_not_have_same_ordering_as
      value: $referenced_encounter_list
      missing_allowed: true
Operations:
  - operator: ordered_list
    datasets:
      - Encounter
    name: id
    ordered_by: nextId
    reference_order: forward
    id: $encounter_list
  - operator: ordered_list
    datasets:
      - ScheduledActivityInstance
      - ScheduledDecisionInstance
    name: encounterId
    ordered_by: defaultConditionId
    reference_order: forward
    id: $referenced_encounter_list
Sensitivity: Dataset
```
