### ISSUE TITLE
FB0915

### ISSUE THREAD

**Issue by SFJohnson24** [cdisc-org/cdisc-rules-engine#1097]
for FB0915
```yaml
Scope:
  Classes:
    Include:
      - STUDY REFERENCE
  Domains:
    Include:
      - OI
```
the rule is not working with class(STUDY REFERENCE) but working when classes include is set to ALL
