### ISSUE TITLE
Rule blocked: CORERULES-9552 - additional requirements for codelist_terms operation

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/cdisc-rules-engine#1177]
**Links to related JIRA Tickets**
- https://jira.cdisc.org/browse/CORERULES-9552
- https://jira.cdisc.org/browse/CORERULES-9609
- https://jira.cdisc.org/browse/CORERULES-9647
- https://jira.cdisc.org/browse/CORERULES-9653
- https://jira.cdisc.org/browse/CORERULES-9654
- https://jira.cdisc.org/browse/CORERULES-9655
- https://jira.cdisc.org/browse/CORERULES-9656
- https://jira.cdisc.org/browse/CORERULES-9659
- https://jira.cdisc.org/browse/CORERULES-9660
- https://jira.cdisc.org/browse/CORERULES-9661
- https://jira.cdisc.org/browse/CORERULES-9662
- https://jira.cdisc.org/browse/CORERULES-9663
- https://jira.cdisc.org/browse/CORERULES-9664
- https://jira.cdisc.org/browse/CORERULES-9665
- https://jira.cdisc.org/browse/CORERULES-9666
- https://jira.cdisc.org/browse/CORERULES-9671
- https://jira.cdisc.org/browse/CORERULES-9672
- https://jira.cdisc.org/browse/CORERULES-9673
- https://jira.cdisc.org/browse/CORERULES-9678
- https://jira.cdisc.org/browse/CORERULES-9679
- https://jira.cdisc.org/browse/CORERULES-9683
- https://jira.cdisc.org/browse/CORERULES-9684
- https://jira.cdisc.org/browse/CORERULES-9685
- https://jira.cdisc.org/browse/CORERULES-9686
- https://jira.cdisc.org/browse/CORERULES-9687
- https://jira.cdisc.org/browse/CORERULES-9688
- https://jira.cdisc.org/browse/CORERULES-9689
- https://jira.cdisc.org/browse/CORERULES-9690
- https://jira.cdisc.org/browse/CORERULES-9691
- https://jira.cdisc.org/browse/CORERULES-9692
- https://jira.cdisc.org/browse/CORERULES-9693
- https://jira.cdisc.org/browse/CORERULES-9696
- https://jira.cdisc.org/browse/CORERULES-9950
- https://jira.cdisc.org/browse/CORERULES-9959
- https://jira.cdisc.org/browse/CORERULES-9962
- https://jira.cdisc.org/browse/CORERULES-9968
- https://jira.cdisc.org/browse/CORERULES-9969
- https://jira.cdisc.org/browse/CORERULES-9972
- https://jira.cdisc.org/browse/CORERULES-9973
- https://jira.cdisc.org/browse/CORERULES-9976
- https://jira.cdisc.org/browse/CORERULES-9992
- https://jira.cdisc.org/browse/CORERULES-9993
- https://jira.cdisc.org/browse/CORERULES-10000
- https://jira.cdisc.org/browse/CORERULES-10001
- https://jira.cdisc.org/browse/CORERULES-10002
- https://jira.cdisc.org/browse/CORERULES-10003
- https://jira.cdisc.org/browse/CORERULES-10007
- https://jira.cdisc.org/browse/CORERULES-10008
- https://jira.cdisc.org/browse/CORERULES-10009
- https://jira.cdisc.org/browse/CORERULES-10010
- https://jira.cdisc.org/browse/CORERULES-10011
- https://jira.cdisc.org/browse/CORERULES-10016
- https://jira.cdisc.org/browse/CORERULES-10017
- https://jira.cdisc.org/browse/CORERULES-10018
- https://jira.cdisc.org/browse/CORERULES-10019
- https://jira.cdisc.org/browse/CORERULES-10022
- https://jira.cdisc.org/browse/CORERULES-10023
- https://jira.cdisc.org/browse/CORERULES-10026
- https://jira.cdisc.org/browse/CORERULES-10030
- https://jira.cdisc.org/browse/CORERULES-10327

**Rule Information**
- **Standard**: USDM
- **Rule ID**: DDF00051
- **Rule Description**: A timing's type must be specified using the Timing Type Value Set Terminology (C201264) DDF codelist.

**Describe the problem**
There are lots of USDM terminology checking rules - similar to DDF00051 - and they're all specified in a similar way (hence the long list of related JIRA issues).

In USDM data, coded information is stored in the `Code` class, which contains the following attributes:
- `codeSystem`: a reference to the type of terminology used. This should be "http://www.cdisc.org" for CDISC terminology.
- `codeSystemVersion`: an indication of which version of the referenced code system/terminology is used. For CDISC terminology, this will be the date of the terminology package used (e.g., "2024-09-27").
- `code`: the code value. For CDISC terminology, this will be the C-code.
- `decode`: the decode value. For CDISC terminology, this should be the submission value associated with the C-code in the relevant codelist.

In order to confirm that a specific attribute is coded according to a specific CDISC codelist, there are a number of things that need to be checked:
1. The correct value is used for `codeSystem` (i.e., the data correctly indicates that CDISC terminology is used). This can be done by using an operator such as `equal_to` to confirm the value matches the expected "http://www.cdisc.org".
2. A valid terminology version is specified.  This can (now) be done by using the (updated) `valid_codelist_dates` operation to retrieve the dates for relevant terminology packages, and then use an operator such as `is_contained_by` to confirm that the value of `codeSystemVersion` is valid.
3. The `code` and `decode` values must be valid and corresponding:
    1. For non-extensible codelists:
        - The `code` must be one of the codes in the specified codelist **in the version of the terminology specified in `codeSystemVersion`**
        -  The `code` value must match the code value for the submission value matching the value of `decode` in the specified codelist **in the version of the terminology specified in `codeSystemVersion`**
        -  The `decode` must be one of the decodes in the specified codelist **in the version of the terminology specified in `codeSystemVersion`**
        -  The `decode` value must match the submission value for the code matching the value of `code` in the specified codelist **in the version of the terminology specified in `codeSystemVersion`**
    2. For extensible codelists:
        - Either both `code` and `decode` should not match any code or submission value (respectively, case insensitive) in the specified codelist **in the version of the terminology specified in `codeSystemVersion`**
        - Or the `code` and `decode` value should be valid and corresponding (as described for non-extensible codelists above) for the specified codelist **in the version of the terminology specified in `codeSystemVersion`**.

The `codelist_terms` operation currently allows codes and submission values to be retrieved from a specified codelist, but it does not:
- Allow terminology package(s) or version(s) to be specified when retrieving the information (it either uses the terminology package specified in the `codelists` parameter at runtime, or it just uses the first (latest) terminology package).
- Allow retrieved information to be merged back onto the check dataset by specific variables - the (same) list of retrieved codes/terms is attached to every row in the check dataset.

**Describe the solution**
The following additional functionality should therefore be added to the `codelist_terms` operation:
1. Add a new optional operation, `ct_package_types`, that can be used to override the standard to determine which types of terminology package should be used for checking.  This parameter and the standard specified at runtime (or in the rule header) should be used in a similar way to their use in `valid_codelist_dates` - if `ct_package_types` is not specified, standard is used to retrieve the relevant package types from a look-up.
2. Add a new optional operation parameter (e.g., `ct_package_versions`) to allow specification of terminology package versions to be specified.  This should be a list parameter that accepts ISO8601 date values and should be used (in combination with the result of processing standard/`ct_package_types`) to determine which terminology package(s) should be used.
    - If this parameter is not used, the original processing should be applied to pick the relevant terminology package(s) (i.e., as specified in `codelists` or the first available).
    - If this parameter is specified, the terminology package version should be included in an additional variable (e.g., `version`) in the retrieved data so that it's available for grouping (see below).  If a value is not a valid terminology package date for the relevant terminology package type, it should just be ignored (no error reported and no information retrieved for that version).

    Note that it should be possible to output from another operation (that produces a list - e.g., `distinct`) as the value of this  parameter. This will allow retrieval of codelist information only for the versions specified in the `codeSystemValue` attribute.
3. Add the `group` operation parameter and use it to group retrieved records by the specified variable(s). Functionality should be the same as for the `distinct` and `record_count` operations. The operator should return a unique list of the specified type of information within each combination of grouping variable(s) values. It should be possible to group retrieved information by any combination of:
    - Terminology package version
    - Codelist code (possibly useful if more than one codelist is specified)
    - Codelist name (possibly useful if more than one codelist is specified)
    - Term code
    - Term term/submission value
4. Add the `group_aliases` operation parameter to allow specified grouping variables to be renamed allowing merging of retrieved (grouped) information with the check dataset. Functionality should be the same as for the `distinct` and `record_count` operations.

**Proposed rule logic**
```yaml
Check:
  all:
    - name: instanceType
      operator: equal_to
      value: 'Timing'
    - name: rel_type
      operator: equal_to
      value: 'definition'
    - name: type
      operator: equal_to
      value: true
    - not:
        all:
          - name: type.codeSystem
            operator: equal_to
            value: 'http://www.cdisc.org'
          - name: type.codeSystemVersion
            operator: is_contained_by
            value: $valid_versions
          - any:
              - all:
                  - name: $codelist_extensible
                    operator: equal_to
                    value: true
                  - any:
                      - all:
                          - name: type.code
                            operator: is_not_contained_by_case_insensitive
                            value: $valid_codes
                          - name: type.decode
                            operator: is_not_contained_by_case_insensitive
                            value: $valid_decodes
                      - all:
                          - name: type.code
                            operator: is_contained_by
                            value: $valid_codes
                          - name: type.decode
                            operator: is_contained_by
                            value: $decode_for_code
                          - name: type.decode
                            operator: is_contained_by
                            value: $valid_decodes
                          - name: type.code
                            operator: is_contained_by
                            value: $code_for_decode
              - all:
                  - name: $codelist_extensible
                    operator: equal_to
                    value: false
                  - name: type.code
                    operator: is_contained_by
                    value: $valid_codes
                  - name: type.decode
                    operator: is_contained_by
                    value: $decode_for_code
                  - name: type.decode
                    operator: is_contained_by
                    value: $valid_decodes
                  - name: type.code
                    operator: is_contained_by
                    value: $code_for_decode
Operations:
  - id: $code_system_versions
    name: type.codeSystemVersion
    operator: distinct
  - id: $valid_versions
    operator: valid_codelist_dates
    ct_package_types:
      - DDF
  - codelist: "Timing Type Value Set Terminology"
    id: $codelist_extensible
    operator: codelist_extensible
    ct_package_versions: $code_system_versions
  - codelists:
      - "Timing Type Value Set Terminology"
    group:
      - version
    group_aliases:
      - type.codeSystemVersion
    id: $valid_codes
    level: term
    operator: codelist_terms
    returntype: code
    ct_package_types:
      - DDF
    ct_package_versions: $code_system_versions
  - codelists:
      - "Timing Type Value Set Terminology"
    group:
      - version
    group_aliases:
      - type.codeSystemVersion
    id: $valid_decodes
    level: term
    operator: codelist_terms
    returntype: value
    ct_package_types:
      - DDF
    ct_package_versions: $code_system_versions
  - codelists:
      - "Timing Type Value Set Terminology"
    group:
      - version
      - code
    group_aliases:
      - type.codeSystemVersion
      - type.code
    id: $decode_for_code
    level: term
    operator: codelist_terms
    returntype: value
    ct_package_types:
      - DDF
    ct_package_versions: $code_system_versions
  - codelists:
      - "Timing Type Value Set Terminology"
    group:
      - version
      - value
    group_aliases:
      - type.codeSystemVersion
      - type.decode
    id: $code_for_decode
    level: term
    operator: codelist_terms
    returntype: code
    ct_package_types:
      - DDF
    ct_package_versions: $code_system_versions
```
**Dataset files that can be used to test the new feature**:
- [Datasets.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFg0Q1E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--91b6d73773b628674bcea39665c895cec144d300/Datasets.xlsx)
- [Datasets.json](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGI0Q1E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--721300d869466b661d39bcc2ce20c00f75d2ebb8/Datasets.txt)

(Both files contain the same information)

**Comment by ASL-rmarshall** [comment]
@gerrycampion No. The codelist is not specified in the data (only the code system and version are specified in the data). The Codelist therefore has to be specified in the rule (eg in the codelists parameter of the codelist_terms operation).  Each codelisted attribute will have a separate rule like the one above.

**Comment by gerrycampion** [comment]
@ASL-rmarshall 
Ah, that's right. Instead of a rule for each instance type, shouldn't we use a lookup table? Something like this: https://github.com/cdisc-org/usdm/blob/main/src/usdm_excel/data/cdisc_ct_config.yaml

**Comment by ASL-rmarshall** [comment]
@gerrycampion I agree that using a CT lookup table feels like it would be more efficient.  However, there'd have to be a number of considerations:

- If using a lookup table (or similar):
    1. The lookup table would need to be reliable.  I'm not sure how or when the file you linked is maintained.  A possible alternative might be the [dataStructure.yml](https://github.com/cdisc-org/DDF-RA/blob/main/Deliverables/UML/dataStructure.yml) file, that's automatically updated whenever there are changes to the model or CT (or API).
    2. The lookup table would also need to be tied explicitly to the version of USDM so that USDM v3 rules only access the terminology defined in USDM v3 and USDM v4 rules only access USDM v4 terminology.
    3. There'd need to be processing done to retrieve the relevant information from the lookup file and to get it into a format that's usable. Both the files we've suggested record the C-code for each codelist, but the `codelist_terms` operation currently only accepts the codelist submission value as a lookup key.

    If there were versioned definitions of the USDM model (including links between attributes and terminology) in the CDISC library, we could theoretically use some of the existing CORE functionality to retrieve the information we need. However, there's previously been resistance to the idea of putting USDM into the Library.
- If using a reduced set of rules (that rely on a lookup table):
    1. We'd have to figure out how to:
        - Retrieve the list of class/attributes that have terminology - to be used in the terminology lookup so we can apply the checking
        - Associate the retrieved terminology with the relevant attribute to be checked
    3. The set of output variables to be reported with each identified terminology issue is not always the same.  The output variables need to give context to where the error is identified.  For codes used in the `AliasCode` class, we'd need to include information from the parent class to give an error the necessary context information.  This would usually require a table join, but we wouldn't know which table to join to (unless we had another lookup table or similar...).
- Impact of defined rule specifications:
    - We've already published the defined set of rules for USDM v3, so we'd be reluctant to change these.
    - We're in the process of publishing the v4 rule specification, so a significant change to the terminology rules is likely to have an impact on timelines.

Based on all of these, I think it's probably more pragmatic to have a separate rule for each codelisted attribute.

**Comment by ASL-rmarshall** [comment]
@gerrycampion Thinking about point iii in the first bullet above, I'm wondering whether we should (also) have the ability to look up terms based on the codelist C-code.  Theoretically, it's possible for the codelist submission value to change between terminology package versions, while the C-code should remain the same so using C-codes to specify codelists in the operation metadata might be more robust and allow more flexibility.  Looking at the code, it looks like the `codelists` parameter could be revised relatively easily to accept either submission values or C-codes with the lookup being done by submission value first in `submission_lookup` and then, if not found, by C-code in the top-level dictionary.  What do you think?

**Comment by gerrycampion** [comment]
This is my plan so far for giving the option to provide a lookup table and then to use the codelist c-code:
```yaml
Operations:
  - id: $codelist_code
    operator: map
    map: #This can be a large lookup table. Just 2 examples for now
      - parent_entity: Timing
        parent_rel: type
        output: C201264
      - parent_entity: Timing
        parent_rel: relativeToFrom
        output: C201265
  - id: $codelist_extensible
    operator: codelist_extensible
    package: ddfct
    version: codeSystemVersion
    codelist_code: $codelist_code
```
