### ISSUE TITLE
Rule blocked: CORERULES-9422

### ISSUE THREAD

**Issue by aniemes** [cdisc-org/cdisc-rules-engine#1198]
- Attach test dataset files that can be used to test the new feature
- Replace the "###" in the issue title with the primary JIRA ticket number for the rule. 
- Fill in the following information

**Links to related JIRA Tickets**
- https://jira.cdisc.org/projects/CORERULES/issues/CORERULES-9422
- https://jira.cdisc.org/projects/CORERULES/issues/CORERULES-9220

[unit-test-coreid-FB1801-negative_01.xlsx](https://github.com/user-attachments/files/20595679/unit-test-coreid-FB1801-negative_01.xlsx)

**Rule Information**
- **Standard**: FDA
- **Rule ID**: FB1801/FB1901
- **Rule Description**: The length of the variable is longer than the data within the variable

**Describe the problem**
We need a way to find the largest element of a single variable
We need a way to iterate through the variables in each dataset

**Describe the solution**
If the engine could search through all elements for a given variable, we could use this to compare this against the variable_size operator.  If the engine could iterate through the list of variables we could use the previous check for all of the variables and compare them in this way.

**Proposed rule logic**
```
Check:
  all:
    - name: variable_size
      operator: less_than_or_equal_to
      value: $size
....
Operations:
  - id: $size
    operator: largest_variable_value
```
