### ISSUE TITLE
dy operation sometimes creates invalid json (NaN values)

### ISSUE THREAD

**Issue by chowsanthony** [cdisc-org/cdisc-rules-engine#153]
**Describe the problem**
Currently $variables defined in Operations can not be used in the Output Variables section. They can be useful to show users the calculated/dervied values expected.

**Describe the solution**
Allow $variables defined in Operations be used in the Output Variables section.

**Proposed rule logic**
```yaml
Check:
  all:
    - name: --STDY
      operator: not_equal_to
      value: $val_stdy
Operations:
  - name: RFSTDTC
    operator: dy
    domain: DM
    id: $val_stdy
Outcome:
  Message: STDY is not calculated correctly.
  Output Variables:
    - USUBJID
    - RFSTDTC
    - --STDTC
    - $val_stdy
    - --STDY
```
