### ISSUE TITLE
As VALIDATOR, I want to cross-check my study data against the study define.xml for mismatching dataset labels so that I can stay compliant with SD1325

### ISSUE THREAD

**Issue by chowsanthony** [cdisc-org/cdisc-rules-engine#253]
1. This check applies to SEND, SDTM, and ADaM data
2. This check is IG-version-agnostic.
3. This is case sensitive.

SD1325 in FDA VR v1.6:
- Rule message: Define.xml/dataset description mismatch
- Rule description: Dataset Description in define.xml must match dataset Description.

**Comment by nhaydel** [comment]
Example Rule:

```yaml
Rule Type: Dataset Metadata Check Against Define
Check:
     all:
       -name: dataset_label
        operator: not_equal_to
        value: define_description
```
