### ISSUE TITLE
Rule blocked: CORERULES-206 CORERULES-435

### ISSUE THREAD

**Issue by gcampion-cdisc** [cdisc-org/cdisc-rules-engine#275]
**Links to related JIRA Tickets**
- https://jira.cdisc.org/projects/CORERULES/issues/CORERULES-206
- https://jira.cdisc.org/projects/CORERULES/issues/CORERULES-435

**Rule Information**
- **Standard**: SDTMIG
- **Rule ID**: CG0336
- **Rule Description**: --CAT matches CDISC Library's domain dataset label (note: this only works for domains in IG, not custom domains)

**Describe the problem**
We need a way to get a domain label from the library ig for the current domain and compare it with the values in a record for the domain.

**Describe the solution**
We probably just need an operation to get the domain label for the current domain from the library ig?

**Proposed rule logic**
```yaml
Rule Type: Record Data
Check:
   all:
      - operator: equal_to
        name: --CAT
        value: $domain_label
Operations:
     - id: $domain_label
       operator: domain_label
```
