### ISSUE TITLE
As VALIDATOR, I want to cross-check my study data against the study define.xml for missing a topic variable in a custom general observation class dataset so that I can stay compliant with CG0320 (Findings), CG0463 (Interventions), CG0464 (Events)

### ISSUE THREAD

**Issue by chowsanthony** [cdisc-org/cdisc-rules-engine#286]
This check applies to only study define using Define-XML v2.1

### For CG0320 (Findings)

When:
1. `ItemGroupDef[@def:IsNonStandard]` is "Yes"
2. `ItemGroupDef/def:Class` is "FINDINGS" 

Then check if:
1. --TESTCD exists as one of the ItemDef for the corresponding ItemGroupDef
2. --TESTCD is a variable that exists in the dataset

### For CG0463 (Interventions)
When:
1. `ItemGroupDef[@def:IsNonStandard]` is "Yes"
2. `ItemGroupDef/def:Class` is "INTERVENTIONS" 

Then check if:
1. --TRT exists as one of the ItemDef for the corresponding ItemGroupDef
2. --TRT is a variable that exists in the dataset

### For CG0464 (Events)
When:
1. `ItemGroupDef[@def:IsNonStandard]` is "Yes"
2. `ItemGroupDef/def:Class` is "EVENTS" 

Then check if:
1. --TERM exists as one of the ItemDef for the corresponding ItemGroupDef
2. --TERM is a variable that exists in the dataset

AC:

- Be able to execute a rule with the following logic:
```
Rule Type: DefineDomainMetadata

# 
define_domain_is_non_standard
define_domain_class
define_domain_variables # ex: [TESTCD, ...]
....
#

Check:
 name: define_domain_is_non_standard
 operator: equal_to
 value: "Yes"
 name: define_domain_class
 operator: equal_to
 value: "FINDINGS'
 name: $testcd_exists_in_dataset
 operator: equal
 value: true
 name: define_domain_variables
 operator: contains
 value: --TESTCD
 

Operations:
# Needs to be modified to check domain content, not current dataset
 - id: $testcd_exists_in_dataset
 name: "--TESTCD"
 operator: variable_exists
```

- A new rule type exists for getting the domain metadata from the define file.
- variable_exists method is modified to check the dataset contents of the current domain rather than assuming the current dataset is the dataset contents
