### ISSUE TITLE
Rule blocked: CORERULES-286

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/cdisc-rules-engine#329]
**Links to related JIRA Tickets**
- https://jira.cdisc.org/projects/CORERULES/issues/CORERULES-286

**Rule Information**
- **Standard**: SDTMIG
- **Rule ID**: CG0288
- **Condition**: TSVCDREF = 'CDISC CT'
- **Rule**: TSVALCD = valid code in the  version identified in TSVCDVER

**Describe the problem**
This deviates from the current way of doing CT lookups given a global study ct version.

**Describe the solution**
When doing CT lookups, there needs to be a way to specify a specific CT version for each lookup. The CT version may or may not match the global study ct version

Option 1:

```yaml
Check:
 - all:
   - name: TSVCDREF
     operator: equal_to
     value: CDISC CT
     value_is_literal: true
  - name: TSVALCD
    operator: is_not_contained_by
    value: $all_ct_term_ccodes
Operations:
- id: $all_ct_term_ccodes
  name: TSVCDVER
  operator: get_all_cdisc_ct_term_ccodes
```

Option 2:

```yaml
Check:
 - all:
   - name: TSVCDREF
     operator: equal_to
     value: CDISC CT
     value_is_literal: true
  - name: TSVALCD
    operator: is_not_contained_by
    value: $all_ct_term_codes
Operations:
- id: $all_ct_term_codes
  name: TSVCDREF
  operator: get_ct_attribute_values
  version: TSVCDVER
  attribute: Term CCODE
```

get_all_ct_term_ccodes returns list of CODES within provided version at the record level [C49488, C49636, C15228...]

If a ct name is not supported, return an empty list
If a ct version does not exist, return an empty list
