### ISSUE TITLE
Rule blocked: CORERULES-249

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/cdisc-rules-engine#397]
**Links to related JIRA Tickets**
- https://jira.cdisc.org/browse/CORERULES-249
- Copied from: https://dev.azure.com/cdisc-org/cdisc-core/_workitems/edit/4757

**Rule Information**
- **Standard**: SDTM
- **Rule ID**: CG0562

**Describe the problem**
There needs to be a way to flatten lists of values in the `is_unique_set` and `is_not_unique_set` operations.

**Proposed rule logic**
```yaml
Check:
  all:
    - name: --REPNUM
      operator: exists
    - name: --REPNUM
      operator: is_not_unique_set
      value:
         - USUBJID
         - --TESTCD
         - $TIMING_VARIABLES
Operations:
  - id: $TIMING_VARIABLES
    name: Role
    value: Timing
    operator: library_variables
```

In this example, we need `value` to represent a flat list containing `USUBJID`, `--TESTCD`, and all of the values within the `$TIMING_VARIABLES` reference.
