### ISSUE TITLE
Rule blocked: CORERULES-12

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/cdisc-rules-engine#412]
**Links to related JIRA Tickets**
- https://jira.cdisc.org/browse/CORERULES-12

**Rule Information**
- **Standard**: SDTM
- **Rule ID**: CG0022
```yaml
# Variable: --LNKGRP
# Condition: --LNKGRP present in a domain
# Rule: --LNKGRP present in another domain
Check:
  all:
    - name: --LNKGRP
      operator: exists
    - name: $VARIABLE_COUNT
      operator: less_than
      value: 2 
Core:
  Id: CDISC.SDTMIG.CG0022
  Version: '1'
  Status: Draft
Description: Verify that when --LNKGRP is present in one domain it is also present
  in another domain.
Operations:
  - id: $VARIABLE_COUNT
    name: --LNKGRP
    operator: variable_count
Outcome:
  Message: --LNKGRP variable is not found in any of the other domains.
  Output Variables:
    - --LNKGRP
    - $VARIABLE_COUNT
Rule Type: Record Data
Sensitivity: Dataset
Executability: Fully Executable
Scope:
  Classes:
    Include:
      - ALL
  Domains:
    Include:
      - ALL
```

[unit-test-coreid-CG0022-negative.xlsx](https://github.com/cdisc-org/cdisc-rules-engine/files/11467182/unit-test-coreid-CG0022-negative.xlsx)
[unit-test-coreid-CG0022-positive.xlsx](https://github.com/cdisc-org/cdisc-rules-engine/files/11467186/unit-test-coreid-CG0022-positive.xlsx)

**Describe the bug**
`variable_count` operation not working as expected when using `--` wildcard

**Error returned from Rule Engine**
This line is resolving `--LNKGRP` before the Operations execution: https://github.com/cdisc-org/cdisc-rules-engine/blob/4c6c2e6ea45d855cb8bb6e4359d1a1247ee6a4aa/cdisc_rules_engine/utilities/rule_processor.py#L232
So that this line has no effect:
https://github.com/cdisc-org/cdisc-rules-engine/blob/4c6c2e6ea45d855cb8bb6e4359d1a1247ee6a4aa/cdisc_rules_engine/operations/variable_count.py#L40

**Expected behavior**
The rule runs as expected if we remove the line in rule_processor, but we need to check for unwanted side-effects.
--LNKGRP needs to remain a wildcard before the operation begins so that the operation will check for --LNKGRP in all domains instead of looking for the current-domain resolved variable.

**Possible Solution**
It may help to have original target and resolved target as separate Operation params so that the operation can choose which param to use.
