### ISSUE TITLE
Rule blocked: CORERULES-6940

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/cdisc-rules-engine#422]
**Links to related JIRA Tickets**
- https://jira.cdisc.org/browse/CORERULES-6940

**Rule Information**
- **Standard**: FDA
- **Rule ID**: SD2282

**Describe the bug**
`distinct` operation causes `Object of type set is not JSON serializable` when run from the TestRule endpoint.

**Sample Rule**
```yaml
Core:
  Id: FDA.SDTMIG.SD2282
  Version: '1'
  Status: Draft
Description: "'Therapeutic Area' (THERAREA) record must be populated in Trial Summary (TS) domain. It is an 'FDA Desired' parameter listed in the Technical Conformance Guide (TCG)."
Outcome:
  Message: Missing THERAREA Trial Summary Parameter
  # Output Variables:
  #   - TSPARMCD
Rule Type: Record Data
Sensitivity: Dataset
Scope:
  Classes:
    Include:
      - TRIAL DESIGN
  Domains:
    Include:
      - TS
Executability: Fully Executable
Check:
  all:
    - name: $distinct_tsparmcd
      operator: does_not_contain
      value: THERAREA
      value_is_literal: true
Operations:
  - id: $distinct_tsparmcd
    name: TSPARMCD
    operator: distinct
```

**Test Data**
[unit-test-coreid-SD2282-negative 1.xlsx](https://github.com/cdisc-org/cdisc-rules-engine/files/11567926/unit-test-coreid-SD2282-negative.1.xlsx)

because `$distinct_tsparmcd` is included as a check `name`, it is part of the output, but it is a "set" object that is not json-serializable.
Note that you can workaround the bug by explicitly setting  `Output Variables` that do no include `$distinct_tsparmcd`.

**AC**
All `output variables` that the engine provides should be json-serializable for the TestRule Endpoint
