### ISSUE TITLE
Rule blocked: CORERULES-7  Reporting for dynamic targets

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/cdisc-rules-engine#448]
**Links to related JIRA Tickets**
- https://jira.cdisc.org/browse/CORERULES-7

**Rule Information**
- **Standard**: SDTMIG
- **Rule ID**: CG0014
- **Rule Description**:
  - Condition: Variable Core Status = Required
  - Rule: Variable present in dataset and ^= null

**Describe the problem**
When we have a rule with dynamic targets (names) like the following:
```yaml
Check:
   any:
    - all:
      - operator: variable_metadata_equal_to
        value: Req
        metadata: $var_perm
      - operator: empty
Operations:
     - id: $var_perm
       operator: variable_library_metadata
       name: core
```
 we don't have the offending variable names and values identified in the report (`AETERM`):
```json
{
  "value": {
    "STUDYID": "ABC123",
    "DOMAIN": "AE",
    "USUBJID": "123101",
    "AESEQ": 1,
    "AETERM": "",
    "AEMODIFY": "HEADACHE",
    "AEDECOD": "Headache",
    "...": "...",
    "$var_perm": {
      "STUDYID": "Req",
      "DOMAIN": "Req",
      "USUBJID": "Req",
      "SPDEVID": "Perm",
      "AESEQ": "Req",
      "AEGRPID": "Perm",
      "AEREFID": "Perm",
      "AESPID": "Perm",
      "AETERM": "Req",
      "AEMODIFY": "Perm",
      "AELLT": "Exp",
      "AELLTCD": "Exp",
      "AEDECOD": "Req",
      "...": "..."
    },
    "results": true
  },
  "row": 1,
  "USUBJID": "123101",
  "SEQ": 1
}
```

**Describe the solution**
- when dynamic targets (check operators with no names) are used and a rule violation is triggered, the name and value of the dynamic target should be provided in the output report
- there should also be a way to specify the dynamic targets within the "Outcome.Output Variables"

For the full rule sample, you can see CG0014 and negative test data in production or refer to the package here:

[Rule.zip](https://github.com/cdisc-org/cdisc-rules-engine/files/11885250/Rule.zip)

_Originally posted by @gerrycampion in https://github.com/cdisc-org/cdisc-rules-engine/pull/446#discussion_r1242590374_
