### ISSUE TITLE
Rule blocked: CORERULES-38

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/cdisc-rules-engine#498]
**Links to related JIRA Tickets**
- https://jira.cdisc.org/browse/CORERULES-38

**Rule Information**
- **Standard**: SDTMIG
- **Rule ID**: CG0001
- **Rule Description**:
Condition: Not custom domain
Rule: DOMAIN = valid Domain Code published by CDISC

**Describe the problem**
There needs to be a way for the rule type:
`Dataset Metadata Check against Define XML`
to access the following metadata: `dataset_domain` and `define_dataset_domain`

**Proposed rule logic**
```yaml
Rule Type: Dataset Metadata Check against Define XML
Check:
  all:
    - name: define_dataset_is_non_standard
      operator: not_equal_to
      value: true
    - name: DOMAIN
      operator: does_not_use_valid_codelist_terms
      value: dataset_domain
```
