### ISSUE TITLE
Rule blocked: CORERULES-150

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/cdisc-rules-engine#518]
**Links to related JIRA Tickets**
- https://jira.cdisc.org/browse/CORERULES-150

**Rule Information**
- **Standard**: SDTMIG
- **Rule ID**: CG0174
- **Rule Description**: 
Condition: Related record present in parent domain dataset
Rule: FAOBJ in (--TERM, --TRT, --DECOD)

**Describe the problem**
There needs to be a way to use relrec to join an FA domain to its parent domain in order to write a rule for CG0174

**Proposed rule logic**
** Check Logic is incomplete for CG0174 **
```yaml
Check:
  all:
    - any:
        - name: --TERM
          operator: exists
        - name: --DECOD
          operator: exists
        - name: --TRT
          operator: exists
    - all:
        - name: FAOBJ
          operator: not_equal_to
          value: --TERM
        - name: FAOBJ
          operator: not_equal_to
          value: --DECOD
        - name: FAOBJ
          operator: not_equal_to
          value: --TRT
Match Datasets:
  - Name: RELREC
    Is Relationship: true
```

**Sample Positive/Negative Test Data**
See sample relrec, FA, AE data in sharepoint here:
Documents - CORE Rules\unitTesting\Samples and Templates\CDISCPILOT01\Clean\excel

The primary missing piece is the ability to match datasets using the relrec dataset.
To match on relrec, Find all sets of relrec rows where RDOMAIN is the current domain, grouped by RELID.
Given the matching relrec rows, match the set of datasets in RDOMAIN on the variables provided in IDVAR, along with USUBJID.
