### ISSUE TITLE
Rule blocked: CORERULES-180

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/cdisc-rules-engine#521]
**Links to related JIRA Tickets**
- https://jira.cdisc.org/browse/CORERULES-180

**Rule Information**
- **Standard**: SDTMIG
- **Rule ID**: CG0209
- **Rule Description**:
Condition: Not last record
Rule: SEENDTC ^= null

**Describe the problem**
There needs to be a way to sort records when using `empty_within_except_last_row`

**Describe the solution**
Allow for `ordering` parameter for the `empty_within_except_last_row` operator. Refer to `has_next_corresponding_record` for similar functionality.

**Proposed rule logic**
```yaml
Check:
  all:
    - name: SEENDTC
      operator: empty_within_except_last_row
      ordering: SESTDTC
      value: USUBJID
```
