### ISSUE TITLE
Rule blocked: CORERULES-256

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/cdisc-rules-engine#604]
**Links to related JIRA Tickets**
- https://jira.cdisc.org/browse/CORERULES-256

**Rule Information**
- **Standard**: SDTMIG
- **Rule ID**: CG0651
- **Rule Description**:
Variable: GEN
Condition: Variable Core Status = Permissible and data is planned to be collected
Rule: Variable present in dataset
Logically, this check tests:
if a library variable exists in the define, 
it should exist in the datasets

**Describe the problem**
Need a new Rule Type: `Variable Metadata Check against Define XML and Library Metadata`

**Describe the solution**
This rule type should do a full outer join of the library variable metadata, define variable metadata, and dataset variable metadata

**Proposed rule logic**
```yaml
Rule Type: Variable Metadata Check against Define XML and Library Metadata
Check:
  all:
    - name: library_variable_core
      operator: equal_to
      value: Perm
    - name: define_variable_name
      operator: non_empty
    - name: dataset_variable_name
      operator: empty
```
