### ISSUE TITLE
Rule blocked: CORERULES-FDAB054.6

### ISSUE THREAD

**Issue by bdevriendt** [cdisc-org/cdisc-rules-engine#651]
**Links to related JIRA Tickets**
not existing at the moment
- https://jira.cdisc.org/projects/CORERULES/issues/CORERULES-
- https://jira.cdisc.org/projects/CORERULES/issues/CORERULES-

**Rule Information**
- **Standard**: SENDIG
- **Rule ID**: FDAB054.6
- **Rule Description**:  Pool ID should match pool definition for nonclinical data.

**Describe the problem**
The FDAB054 rule can be broken down in multiple sub-rules, one of them being:
For a same POOLDEF.POOLID, there should be more than one value for POOLDEF.USUBJID
          Positive              
|| POOLID ||  USUBJID ||           
||     0001  ||      B0001 ||
||     0001  ||      B0003 ||
||     0001  ||      B0005 ||
||     0001  ||      B0006 || 
||     0002  ||      B0001 ||    
||     0002  ||      B0002 ||       
||     0002  ||      B0003 ||
||     0002  ||      B0005 ||
        Negative
|| POOLID ||  USUBJID ||       
||     0001  ||      B0001 ||
||     0002  ||      B0001 ||
||     0002  ||      B0002 ||
||     0002  ||      B0003 ||
||     0002  ||      B0005 ||
Currently we do not have a way to count the number of distinct values in a specific subset of data.

**Describe the solution**
We would need to be able to retrieve a list of USUBJIDs per POOLID and count how many are present in each list

**Proposed rule logic**
```yaml
Check:
  all:
    - value: '$count'
      operator: 'greater_than'
      value: '1'  
Operation:
  - operator: "count_distinct_values_in_subset"
    domain: "POOLDEF"
    name: "USUBJID"
    id: "$count"
    group:
      - POOLID
```
