### ISSUE TITLE
Rule blocked: SEND105

### ISSUE THREAD

**Issue by JozefAerts** [cdisc-org/cdisc-rules-engine#720]
It looks as the operator "exists" only works on the variable level, and not on the domain/dataset level.
In SEND rule 105, we need to check whether "SPECIES" is present either in TX or TS, but this fails when the TX dataset is not present.
When I use "non_empty" this causes an error:
"error":"An unknown exception has occurred"
"message":"'NoneType' object is not subscriptable"

So, I think we need an additional operator "dataset_exists" or "domain_present" or something like that and the negation of it.

**Comment by alexfurmenkov** [comment]
I've tried to reproduce this issue and looks like there were some updates to the engine since this ticket was created. I am attaching the rule and dataset that I've used to reproduce this issue. 

The thing is that I was unable to reproduce it - right now if the domain is not found in the dataset the engine raises an error `DomainNotFoundError: Operation distinct requires Domain TX but Domain not found in dataset` which is OK in my opinion. 

Please let me know if we still need to do something with the engine. 

p. s. just a preview of the rule operations and `datasets.json`:
```
Operations:
  # gets the distinct values of TSPARMCD
  - domain: TS
    id: $distinct_tsparmcd
    name: TSPARMCD
    operator: distinct
  - domain: TX
    id: $distinct_txparmcd
    name: TXPARMCD
    operator: distinct
```

```
{
    "datasets": [
        {
            "filename": "dm.xpt",
            "label": "Demographics",
            "domain": "DM",
            "variables": [...],
            "records": [...]
        },
        {
            "filename": "ts.xpt",
            "label": "Trial Summary",
            "domain": "TS",
            "variables": [...],
            "records": [...]
        }
    ],
    "standard": {
        "product": "sendig",
        "version": "3-1"
    },
    "codelists": []
}
```

[Rule_SEND105_problem (1).zip](https://github.com/user-attachments/files/23262200/Rule_SEND105_problem.1.zip)
