### ISSUE TITLE
Rule blocked: CORERULES-9568 - add filter for distinct operation

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/cdisc-rules-engine#845]
**Links to related JIRA Tickets**
- https://jira.cdisc.org/projects/CORERULES/issues/CORERULES-9568

**Rule Information**
- **Standard**: USDM
- **Rule ID**: DDF00009
- **Rule Description**: Each schedule timeline must contain at least one anchor (fixed time) - i.e., at least one scheduled activity instance that is referenced by a Fixed Reference timing.

**Describe the problem**
This rule needs to report each record from the ScheduleTimeline dataset where there is no record in the Timing dataset that has all of:
- `parent_id` = `ScheduledTimeline.id`,
- `rel_type` = `"definition"`,
- `type.decode` = `"Fixed Reference"` and
- a value of `relativeFromScheduledInstanceId` that matches the `id` value from any record from the ScheduledActivityInstance dataset that has all of:
    -  `parent_id` = `ScheduledTimeline.id` and
    -  `rel_type` = `"definition"`

The rule cannot be implemented using `Match Datasets` because it is (currently) not possible to filter datasets before merging them.

**Describe the solution**
If filtering functionality is added to the `distinct` operation (in the same way that it's applied for the `record_count` operation), it would be possible to generate two lists of ids, link them both to the parent record in the ScheduleTimeline dataset, compare the lists and report any record where there is no overlap.

As with `record_count`, the updated operation should produce a list of distinct values for every group in the dataset. If there are no records for the group that meet the filtering criteria, then an empty list should be returned for the group.

**Proposed rule logic**
(See DDF00009)
```yaml
Check:
  all:
    - name: instanceType
      operator: equal_to
      value: 'ScheduleTimeline'
    - name: rel_type
      operator: equal_to
      value: 'definition'
    - any:
        - name: $fixed_ref_sched_ins
          operator: empty
        - name: $instances
          operator: empty
        - name: $fixed_ref_sched_ins
          operator: shares_no_elements_with
          value: $instances
Operations:
  - domain: TIMING
    filter:
      rel_type: 'definition'
      type.decode: 'Fixed Reference'
    group:
      - parent_id
    group_aliases:
      - id
    id: $fixed_ref_sched_ins
    name: relativeFromScheduledInstanceId
    operator: distinct
  - domain: SCHEDULEDACTIVITYINSTANCE
    filter:
      rel_type: 'definition'
    group:
      - parent_id
    group_aliases:
      - id
    id: $instances
    name: id
    operator: distinct
```

**Comment by gerrycampion** [comment]
@nickdedonder to provide a list of non-ddf rules that this would apply to

**Comment by SFJohnson24** [comment]
This is applicable to CG0214
per Adam Niemes "For this rule, I need to get the list of VISITNUM where SVUPDES is not empty and compare it against the VISITNUM list from the TV domain.  So for this list:"
![Image](https://github.com/user-attachments/assets/bd68ada8-cc48-46b0-a02e-40cadbc31e51)
I would want to get the 2 & 3.  I tried to implement it like this:
![Image](https://github.com/user-attachments/assets/b078648a-63f5-4d21-af15-f618c3ec1b4c)

This rule would want something similar to what Richard is describing above but would want a wildcard meaning any non-empty value instead of declaring the value in the rule.

**Comment by ASL-rmarshall** [comment]
@SFJohnson24 At the moment, filters are built as simple "variable = value" conditions. If we're considering adding complexity (e.g., allowing wildcards as suggested in the previous comment), I've always wondered if would be feasible to reuse the functionality already available for parsing more complex conditions - i.e., the condition processing that's used for rule validation itself (as applied for the rule `Check`). E.g. to restrict `distinct` based on a non-empty value:
```yaml
Operations:
  - domain: SV
    filter:
      all:
        - name: SVUPDES
          operator: non_empty
    group:
      - VISITNUM
    id: $visnum_unsch
    operator: distinct
```
